name: Crawler

on:
  schedule:
    - cron: '00 16 * * *'
  workflow_dispatch:

jobs:
  crawl:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Python
        uses: actions/setup-python@v4.7.0
        with:
          python-version: '3.11.4'
          cache: 'pip'
          check-latest: true
          cache-dependency-path: '**/requirements.txt'

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip3 install -r requirements.txt
      - name: Set Timezone
        uses: zcong1993/setup-timezone@v1.1.1
        with: 
          timezone: 'Asia/Shanghai'

      - name: Crawl
        run: python3 BingCrawler.py

      - name: Commit
        run: |
          git config --local user.email 393893729@qq.com
          git config --local user.name WangZhiYao
          git add .
          git commit -a -m "Update: `TZ='Asia/Shanghai' date +'%Y-%m-%d %H:%M:%S'`"
          git push
